import type { ScrapedContent } from '../scraper/types';

export interface ProcessOptions {
    includeAI: boolean;
}

export const processContent = (content: ScrapedContent, options: ProcessOptions): string => {
    let textToProcess = "";

    // 1. Extract initial text (Structured or Raw)
    if (content.conversation && content.conversation.length > 0) {
        if (options.includeAI) {
            // Full Conversation (User + AI)
            textToProcess = content.conversation
                .map(turn => `${turn.role === 'user' ? 'User' : 'AI'}: ${turn.content}`)
                .join('\n\n');
        } else {
            // User Only (Attempt)
            textToProcess = content.conversation
                .filter(turn => turn.role === 'user')
                .map(turn => turn.content)
                .join('\n\n');
        }
    }

    // Fallback if structured extraction failed or returned empty
    if (!textToProcess || textToProcess.trim().length === 0) {
        textToProcess = content.rawText || "";
    }

    // 2. SMART INTENT FILTERING (If includeAI is false)
    const isStructured = content.conversation && content.conversation.length > 0;
    console.log("Lotus: Processor - isStructured:", isStructured);
    console.log("Lotus: Processor - Initial textToProcess:", textToProcess);

    if (!options.includeAI && textToProcess.length > 0 && !isStructured) {
        console.log("Lotus: Processor - Running Heuristic Filter (Unstructured Path)");
        const blocks = textToProcess.split(/\n\n+/);

        const filteredBlocks = blocks.filter(block => {
            const lower = block.toLowerCase().trim();
            if (lower.length < 2) return false;

            // SAFETY NET: If it contains strong user intent keywords, PASS IT IMMEDIATELY.
            // This overrides all AI/Noise filters.
            if (/(need|want|make|change|update|remove|add|fix|replace|include|exclude)/i.test(lower)) {
                return true;
            }

            // --- A. AI & NARRATIVE NEGATIVE PATTERNS ---
            // These patterns strongly indicate AI generation or narrative content.
            const aiIndicators = [
                /^here (is|are)/,           // "Here is the code..."
                /^sure,|^certainly/,        // "Sure, I can help..."
                /^as an ai/,                // "As an AI..."
                /^i (have|can|will|understand|apologize)/, // "I have updated...", "I understand..."
                /^(the|this) (code|story|solution|example)/, // "The code shows...", "The story follows..."
                /^output:|^response:/,      // Metadata
                /^once upon a time/,        // Narrative start
                /^in the end/,              // Narrative end
                /chapter \d+/,              // Narrative structure
                /^generated by/             // Watermarks
            ];

            if (aiIndicators.some(p => p.test(lower))) return false;

            // --- B. CODE BLOCK KILLER ---
            // AI responses often contain code blocks. User prompts rarely do (unless pasting).
            // We aggressively filter these to prevent "Here is the code:" + ```code```.
            if (block.includes("```") || (block.includes("import ") && block.includes("from "))) return false;

            // --- C. USER INTENT POSITIVE PATTERNS ---
            // If the block is long (>80 chars), it MUST have a clear "User Intent".
            // Short blocks are allowed to pass (likely follow-up questions).
            if (block.length > 80) {
                const intentPatterns = [
                    // 1. Imperative Verbs (Commands)
                    /^(please )?(write|create|make|fix|debug|explain|generate|draft|compose|list|show|give|provide|tell|analyze|optimize|refactor|add|remove|update|change|modify)/,

                    // 2. Personal Needs (First Person)
                    /^(i|we) (want|need|would like|am looking for|have)/,

                    // 3. Direct Questions
                    /^(how|what|where|when|why|who|can|could|is|are|do|does) /,

                    // 4. Contextual References (My code, This error)
                    /(my|the) (code|error|app|script|function|variable) (is|has|doesn't|fails)/,

                    // 5. Correction/Addition Indicators (Forgiving Mode - No ^ anchor)
                    /(actuall+y|also|but|and|plus|instead|however|wait|this is|i need|i want)/i
                ];

                const hasIntent = intentPatterns.some(p => p.test(lower));

                // SAFETY NET: If it contains strong keywords, let it pass regardless of structure
                if (!hasIntent) {
                    if (/(need|want|make|change|update|remove|add|fix)/i.test(lower)) {
                        return true;
                    }
                }

                if (!hasIntent) {
                    // If it's long and lacks intent, it's likely AI chatter or a story.
                    return false;
                }
            }

            return true;
        });

        if (filteredBlocks.length > 0) {
            return filteredBlocks.map(b => `User: ${b}`).join('\n\n');
        } else {
            return "";
        }
    }

    return textToProcess;
};
