import React, { useState, useEffect } from 'react';
import { Settings, History, HelpCircle, Info, Check, ExternalLink, ArrowLeft, Copy, ThumbsUp, ThumbsDown, RefreshCw, MoreVertical, Mail, FileText, Flag, Volume2, LogOut, Users, Book, Sparkles, Edit2, MessageSquare } from 'lucide-react';
import { PulseCheck } from '../components/PulseCheck';
import { Layout } from '../components/Layout';
import { GenerateButton } from '../components/GenerateButton';
import { Tooltip } from '../components/ui/Tooltip';
import { Button } from '../components/ui/Button';
import { cn } from '../components/ui/Tooltip';
import { generateSummary } from '../services/openai';
import { signInWithGoogle, logout, subscribeToAuthChanges, clearChromeIdentityToken, saveHistoryToFirestore, getHistoryFromFirestore, clearHistoryFromFirestore, saveUserProfile } from '../services/firebase';
import { type User } from 'firebase/auth';
import { identifyUser, trackEvent, resetAnalytics, initAnalytics } from '../services/analytics';

interface HomeViewProps {
    onGenerateComplete?: (summary: string) => void;
}




const CheckboxRow = ({
    label,
    subtext,
    checked,
    onChange
}: {
    label: string;
    subtext: string;
    checked: boolean;
    onChange: () => void;
}) => (
    <div className="flex items-center gap-4 p-2 cursor-pointer group hover:bg-gray-50 rounded-xl transition-colors" onClick={onChange}>
        <div className={cn(
            "w-5 h-5 rounded-md border flex items-center justify-center transition-all duration-200 shrink-0",
            checked ? "bg-black border-black" : "bg-white border-gray-300 group-hover:border-gray-400"
        )}>
            {checked && <Check className="w-3.5 h-3.5 text-white" strokeWidth={3} />}
        </div>
        <div className="flex flex-col select-none">
            <span className="text-sm font-medium text-gray-900">{label}</span>
            <span className="text-xs text-gray-500">{subtext}</span>
        </div>
    </div>
);

type PopupType = 'none' | 'more' | 'profile' | 'metadata' | 'history' | 'settings' | 'help' | 'feedback';

const SummaryToolbar = ({ summary, onEdit, activePopup, onTogglePopup, onRegenerate, user }: {
    summary: string;
    onEdit: () => void;
    activePopup: PopupType;
    onTogglePopup: (type: PopupType) => void;
    onRegenerate: () => void;
    user: User | null;
}) => {
    const [feedback, setFeedback] = useState<'idle' | 'good' | 'bad' | 'copied' | 'doc'>('idle');
    const [goodActive, setGoodActive] = useState(false);
    const [badActive, setBadActive] = useState(false);

    const [isSpeaking, setIsSpeaking] = useState(false);

    const handleGood = () => {
        if (goodActive) {
            setGoodActive(false);
            return;
        }
        setGoodActive(true);
        setBadActive(false);
        setFeedback('good');
        trackEvent('summary_rated', { rating: 'positive', summary_length: summary.length });
        setTimeout(() => setFeedback('idle'), 2000);
    };

    const handleBad = () => {
        if (badActive) {
            setBadActive(false);
            return;
        }
        setBadActive(true);
        setGoodActive(false);
        setFeedback('bad');
        trackEvent('summary_rated', { rating: 'negative', summary_length: summary.length });
        setTimeout(() => setFeedback('idle'), 2000);
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(summary);
        setFeedback('copied');
        setTimeout(() => setFeedback('idle'), 2000);
    };

    const handleListen = () => {
        if ('speechSynthesis' in window) {
            if (isSpeaking) {
                window.speechSynthesis.cancel();
                setIsSpeaking(false);
            } else {
                const utterance = new SpeechSynthesisUtterance(summary);
                utterance.onend = () => setIsSpeaking(false);
                window.speechSynthesis.speak(utterance);
                setIsSpeaking(true);
            }
        }
    };

    const handleDoc = async () => {
        onTogglePopup('none');
        if (!summary) return;

        try {
            // Create HTML for the doc (preserves formatting)
            const htmlContent = `
                <div style="font-family: Arial, sans-serif; font-size: 11pt; line-height: 1.5;">
                    ${summary.replace(/\n/g, '<br>')}
                    <br><br>
                    <hr style="border: 0; border-top: 1px solid #ccc;">
                    <p style="color: #666; font-size: 9pt;">Generated by Summarai</p>
                </div>
            `;

            const blob = new Blob([htmlContent], { type: 'text/html' });
            const textBlob = new Blob([summary], { type: 'text/plain' });

            // Try writing HTML to clipboard
            if (typeof ClipboardItem !== 'undefined') {
                try {
                    // @ts-ignore
                    const data = [new ClipboardItem({
                        'text/html': blob,
                        'text/plain': textBlob,
                    })];
                    await navigator.clipboard.write(data);
                } catch (err) {
                    // Fallback to text only if HTML fails
                    await navigator.clipboard.writeText(summary);
                }
            } else {
                await navigator.clipboard.writeText(summary);
            }

            setFeedback('doc');
            setTimeout(() => setFeedback('idle'), 4000);

            // Set flag for the content script to show the "Paste" guide
            await chrome.storage.local.set({ 'pendingSummaryPaste': true });

            // Open new Google Doc
            window.open('https://docs.google.com/document/create', '_blank');

        } catch (e) {
            console.error("Export failed", e);
            // Ultimate fallback
            window.open('https://docs.google.com/document/create', '_blank');
        }
    };

    const handlePDF = async () => {
        onTogglePopup('none');
        if (!summary) return;

        try {
            const { jsPDF } = await import('jspdf');
            const doc = new jsPDF();

            // Title
            doc.setFontSize(20);
            doc.text("Summary Report", 20, 20);

            // Date
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 30);

            // Content
            doc.setFontSize(12);
            doc.setTextColor(0);

            const splitText = doc.splitTextToSize(summary, 170);
            doc.text(splitText, 20, 40);

            // Footer
            const pageCount = doc.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(10);
                doc.setTextColor(150);
                doc.text('Generated by Summarai', 20, 285);
            }

            const now = new Date();
            const day = String(now.getDate()).padStart(2, '0');
            const month = String(now.getMonth() + 1).padStart(2, '0');
            const year = String(now.getFullYear()).slice(-2); // YY
            const hours = String(now.getHours()).padStart(2, '0');
            const minutes = String(now.getMinutes()).padStart(2, '0');

            const filename = `summarai_${day}.${month}.${year}_${hours}.${minutes}.pdf`;

            doc.save(filename);

            setFeedback('doc'); // Reuse doc feedback for simplicity or add 'pdf'
            setTimeout(() => setFeedback('idle'), 3000);

        } catch (e) {
            console.error("PDF Generation failed", e);
            alert("Failed to generate PDF. Please try again.");
        }
    };


    return (
        <div className="relative">
            <div className="flex items-center gap-1 p-1 bg-white rounded-xl border border-gray-100 shadow-lg min-h-[40px]">

                {/* Good Button */}
                <Tooltip content="Good Response">
                    <Button
                        variant="ghost"
                        size="icon"
                        onClick={handleGood}
                        className={cn(
                            "h-8 w-8 rounded-lg transition-colors shrink-0 focus:outline-none focus:ring-0",
                            goodActive ? "text-black hover:bg-gray-100" : "text-gray-500 hover:bg-gray-50"
                        )}
                    >
                        <ThumbsUp className={cn("w-4 h-4", goodActive && "fill-current")} />
                    </Button>
                </Tooltip>

                {/* Good Feedback Message */}
                {feedback === 'good' && (
                    <div className="overflow-hidden whitespace-nowrap text-[10px] font-medium text-green-600 px-1 animate-fade-in">
                        Thanks for feedback
                    </div>
                )}

                {/* Bad Button */}
                <Tooltip content="Bad Response">
                    <Button
                        variant="ghost"
                        size="icon"
                        onClick={handleBad}
                        className={cn(
                            "h-8 w-8 rounded-lg transition-colors shrink-0 focus:outline-none focus:ring-0",
                            badActive ? "text-black hover:bg-gray-100" : "text-gray-500 hover:bg-gray-50"
                        )}
                    >
                        <ThumbsDown className={cn("w-4 h-4", badActive && "fill-current")} />
                    </Button>
                </Tooltip>

                {/* Bad Feedback Message */}
                {feedback === 'bad' && (
                    <div className="overflow-hidden whitespace-nowrap text-[10px] font-medium text-black px-1 animate-fade-in">
                        Thanks for feedback
                    </div>
                )}

                <div className="w-px h-4 bg-gray-200 mx-0.5 shrink-0" />

                {/* Regenerate */}
                <Tooltip content="Regenerate">
                    <Button
                        variant="ghost"
                        size="icon"
                        onClick={onRegenerate}
                        className="h-8 w-8 hover:bg-gray-50 rounded-lg text-gray-500 shrink-0 focus:outline-none focus:ring-0"
                    >
                        <RefreshCw className="w-4 h-4" />
                    </Button>
                </Tooltip>

                {/* Copy */}
                <Tooltip content="Copy">
                    <Button variant="ghost" size="icon" onClick={handleCopy} className="h-8 w-8 hover:bg-gray-50 rounded-lg text-gray-500 shrink-0 focus:outline-none focus:ring-0">
                        <Copy className="w-4 h-4" />
                    </Button>
                </Tooltip>

                {/* Copy Feedback Message */}
                {feedback === 'copied' && (
                    <div className="overflow-hidden whitespace-nowrap text-[10px] font-medium text-gray-700 flex items-center gap-1 px-1 animate-fade-in">
                        <Check className="w-3 h-3" />
                        Copied
                    </div>
                )}

                {/* Doc Feedback Message */}
                {feedback === 'doc' && (
                    <div className="overflow-hidden whitespace-nowrap text-[10px] font-medium text-blue-600 flex items-center gap-1 px-1 animate-fade-in">
                        <Check className="w-3 h-3" />
                        Copied! Paste in Doc
                    </div>
                )}

                {/* More */}
                <div className="relative shrink-0">
                    <Tooltip content="More">
                        <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => onTogglePopup(activePopup === 'more' ? 'none' : 'more')}
                            className={cn(
                                "h-8 w-8 rounded-lg text-gray-500 hover:bg-gray-50 focus:outline-none focus:ring-0",
                                activePopup === 'more' && "bg-gray-100 text-gray-900"
                            )}
                        >
                            <MoreVertical className="w-4 h-4" />
                        </Button>
                    </Tooltip>
                    {activePopup === 'more' && (
                        <>
                            <div className="fixed inset-0 z-40" onClick={() => onTogglePopup('none')} />
                            <div className="absolute bottom-full right-0 mb-2 w-auto min-w-[200px] bg-white rounded-2xl shadow-xl border border-gray-200 overflow-hidden z-50 flex flex-col py-2 animate-slide-up-fade">
                                <button
                                    onClick={() => {
                                        onEdit();
                                        onTogglePopup('none');
                                    }}
                                    className="flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-200/50 w-full text-left transition-colors font-medium"
                                >
                                    <Edit2 className="w-4 h-4" />
                                    Edit summary
                                </button>
                                <button
                                    onClick={handleListen}
                                    className={cn(
                                        "flex items-center gap-3 px-4 py-2.5 text-sm hover:bg-gray-200/50 w-full text-left transition-colors font-medium",
                                        isSpeaking ? "text-blue-600" : "text-gray-700"
                                    )}
                                >
                                    <Volume2 className={cn("w-4 h-4", isSpeaking && "animate-pulse")} />
                                    {isSpeaking ? 'Stop speaking' : 'Listen'}
                                </button>
                                <button
                                    onClick={handleDoc}
                                    className="flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-200/50 w-full text-left transition-colors font-medium"
                                >
                                    <FileText className="w-4 h-4" />
                                    Export to Docs
                                </button>
                                <button
                                    onClick={handlePDF}
                                    className="flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-200/50 w-full text-left transition-colors font-medium"
                                >
                                    <FileText className="w-4 h-4" />
                                    Download PDF Report
                                </button>
                                <button
                                    onClick={() => {
                                        const greeting = user?.displayName ? `Hi ${user.displayName.split(' ')[0]},\n\n` : '';
                                        window.open(`https://mail.google.com/mail/?view=cm&fs=1&body=${encodeURIComponent(greeting + summary)}`, '_blank');
                                    }}
                                    className="flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-200/50 w-full text-left transition-colors font-medium"
                                >
                                    <Mail className="w-4 h-4" />
                                    Draft in Gmail
                                </button>
                                <button
                                    onClick={() => window.open('https://superextension.in/report', '_blank')}
                                    className="flex items-center gap-3 px-4 py-2.5 text-sm text-gray-700 hover:bg-gray-200/50 w-full text-left transition-colors font-medium"
                                >
                                    <Flag className="w-4 h-4" />
                                    Report legal issue
                                </button>

                                <div className="my-1 border-t border-gray-200" />

                                <div className="flex items-center gap-3 px-4 py-2 text-sm text-gray-400 w-full text-left font-medium select-none">
                                    <Sparkles className="w-4 h-4" />
                                    Model: GPT-4o-mini
                                </div>
                            </div>
                        </>
                    )}
                </div>
            </div>
        </div>
    );
};

export const HomeView: React.FC<HomeViewProps> = () => {
    const [genState, setGenState] = useState<'idle' | 'generating' | 'completed'>('idle');
    const [includeAI, setIncludeAI] = useState(false);
    const [analyzeImages, setAnalyzeImages] = useState(false);
    const [activePopup, setActivePopup] = useState<PopupType>('none');
    const [summary, setSummary] = useState<string | null>(null);
    const [isEditing, setIsEditing] = useState(false);
    const [isRegenerating, setIsRegenerating] = useState(false);
    const [summaryType, setSummaryType] = useState<'TXT' | 'JSON' | 'XML'>('TXT');
    const [provider, setProvider] = useState<'openai' | 'google' | 'auto'>('auto');
    const [user, setUser] = useState<User | null>(null);
    const [isPro, setIsPro] = useState(false);
    const [history, setHistory] = useState<any[]>([]);

    useEffect(() => {
        initAnalytics();
        trackEvent('extension_opened');

        chrome.storage.local.get(['isPro'], (result) => {
            setIsPro(!!result.isPro);
        });
    }, []);

    // Reset button state when options change (disable auto-regenerate)
    useEffect(() => {
        if (summary && genState === 'completed') {
            setGenState('idle');
        }
    }, [includeAI, analyzeImages]);



    // ... (inside useEffect)

    useEffect(() => {
        const unsubscribe = subscribeToAuthChanges(async (u: User | null) => {
            setUser(u);
            if (u) {
                identifyUser(u.uid, u.email || undefined);
                saveUserProfile(u); // Save user profile to Firestore

                // Load Cloud History
                const cloudHistory = await getHistoryFromFirestore(u.uid);
                if (cloudHistory && cloudHistory.length > 0) {
                    setHistory(cloudHistory);
                    chrome.storage.local.set({ history: cloudHistory });
                }
            } else {
                resetAnalytics();
            }
        });
        return () => unsubscribe();
    }, []);

    // Load API Key, Provider, and History from storage on mount
    React.useEffect(() => {
        chrome.storage.local.get(['summaryType', 'provider', 'history'], (result) => {
            if (result.summaryType) {
                setSummaryType(result.summaryType as 'TXT' | 'JSON' | 'XML');
            }
            if (result.provider) {
                setProvider(result.provider as 'openai' | 'google' | 'auto');
            }
            if (result.history && Array.isArray(result.history)) {
                setHistory(result.history);
            }
        });
    }, []);

    const handleProviderChange = (newProvider: 'openai' | 'google' | 'auto') => {
        setProvider(newProvider);
        chrome.storage.local.set({ provider: newProvider });
        trackEvent('provider_changed', { provider: newProvider });
    };

    const handleLogin = async () => {
        try {
            await signInWithGoogle();
            setActivePopup('none');
        } catch (e: any) {
            console.error("Login Error:", e);
            alert(`Login failed: ${e.message}\n\nCheck console for details.`);
        }
    };

    const handleLogout = async () => {
        await logout();
        setActivePopup('none');
    };

    const handleSwitchAccount = async () => {
        await clearChromeIdentityToken();
        handleLogin();
    };

    const handleViewHistoryItem = (item: any) => {
        setSummary(item.summary);
        setGenState('completed');
        setActivePopup('none');
        trackEvent('history_item_viewed', { item_id: item.id });
    };

    const handleHelpAction = (action: string) => {
        window.open(`https://superextension.in/help?topic=${action}`, '_blank');
        setActivePopup('none');
        trackEvent('help_action_clicked', { action });
    };

    const handleGenerate = async (additionalInfo?: string, format?: 'paragraph' | 'points', tone?: 'normal' | 'professional' | 'creative') => {

        setGenState('generating');

        try {
            // 1. Get Active Tab
            const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
            if (!tab.id) throw new Error("No active tab found");

            // 2. Scrape Content
            const response = await chrome.tabs.sendMessage(tab.id, { action: 'getPageContent', includeImages: analyzeImages });

            if (!response) {
                throw new Error("Failed to scrape content. Refresh the page and try again.");
            }

            // Prepare content
            let textToAnalyze = response.rawText || "";

            if (response.conversation && response.conversation.length > 0) {
                if (includeAI) {
                    // Include BOTH User and AI
                    textToAnalyze = response.conversation
                        .map((turn: any) => `${turn.role === 'user' ? 'User' : 'AI'}: ${turn.text}`)
                        .join('\n\n');
                } else {
                    // Filter for USER prompts only
                    textToAnalyze = response.conversation
                        .filter((turn: any) => turn.role === 'user')
                        .map((turn: any) => `User: ${turn.text}`)
                        .join('\n\n');
                }
            }

            // 3. Generate Summary
            console.log("Calling generateSummary with:", { includeAI, format: format || summaryType, provider, images: response.images?.length, tone });

            // Create a promise for the minimum animation time (e.g., 2.5 seconds)
            const animationPromise = new Promise(resolve => setTimeout(resolve, 2500));

            // Run generation and animation timer in parallel
            const [generatedSummary] = await Promise.all([
                generateSummary(textToAnalyze, {
                    includeAI,
                    format: format || summaryType, // Use passed format or default
                    length: 'medium',
                    apiKey: '',
                    provider,
                    images: analyzeImages ? response.images : undefined,
                    tone: tone // Pass tone
                }, provider, additionalInfo),
                animationPromise
            ]);

            setSummary(generatedSummary);
            setGenState('completed');
            setIsRegenerating(false);

            // Save to History
            const newHistoryItem = {
                id: Date.now(),
                summary: generatedSummary,
                date: new Date().toISOString(),
                preview: generatedSummary.slice(0, 100) + "..."
            };

            // 1. Save Local
            chrome.storage.local.get(['history'], (result) => {
                const currentHistory = (result.history as any[]) || [];
                const updatedHistory = [newHistoryItem, ...currentHistory].slice(0, 50);
                chrome.storage.local.set({ history: updatedHistory });
                setHistory(updatedHistory);
                setHistory(updatedHistory);
            });

            // Increment Summarize Count for Pulse Check
            chrome.storage.local.get(['summarizeCount'], (res) => {
                const currentCount = (res.summarizeCount as number) || 0;
                chrome.storage.local.set({ summarizeCount: currentCount + 1 });
            });

            // 2. Save Cloud (if logged in)
            if (user) {
                saveHistoryToFirestore(user.uid, newHistoryItem);
            }

            trackEvent('summary_generated', {
                type: summaryType,
                length: summary ? summary.length : 0,
                is_pro: isPro,
                include_ai: includeAI,
                analyze_images: analyzeImages,
                format: format || summaryType,
                tone: tone || 'normal',
                provider: provider
            });
        } catch (error: any) {
            console.error("Generation failed:", error);
            const msg = error.message || "Failed to generate summary";

            if (msg.includes("Could not establish connection") || msg.includes("Receiving end does not exist") || msg.includes("Extension context invalidated")) {
                if (confirm("Connection lost. This happens when the extension is updated.\n\nClick OK to refresh the page and fix it.")) {
                    chrome.tabs.query({ active: true, currentWindow: true }).then(([tab]) => {
                        if (tab.id) chrome.tabs.reload(tab.id);
                    });
                }
            } else {
                alert(msg);
            }

            setGenState('idle');
            trackEvent('generation_failed', { error: msg });
        } finally {
            setIsRegenerating(false);
        }
    };

    const handleClearHistory = () => {
        if (confirm("Are you sure you want to clear your history?")) {
            chrome.storage.local.set({ history: [] });
            setHistory([]);

            if (user) {
                clearHistoryFromFirestore(user.uid);
            }
        }
    };

    const handleRegenerate = () => {
        setIsRegenerating(true);
        trackEvent('regenerate_clicked');
        handleGenerate();
    };

    const handleBack = () => {
        setSummary(null);
        setGenState('idle');
    };


    return (
        <Layout>
            <div className="flex flex-col h-full relative">
                {/* Summary Box - Takes up remaining space */}
                <div className="flex-1 min-h-0 mb-4">
                    <div className="w-full h-full flex flex-col overflow-hidden relative border border-gray-200 rounded-2xl">
                        {/* Top Right: Beta & Profile - Always Visible */}
                        <div className="absolute top-4 right-4 z-50 flex items-center gap-2">
                            <span className="px-1.5 py-0.5 rounded-md bg-blue-50 text-blue-600 text-[10px] font-bold uppercase tracking-wider border border-blue-100 shadow-sm">
                                Beta
                            </span>

                            <Tooltip content="Profile" side="bottom">
                                <div
                                    className="w-8 h-8 rounded-full bg-gray-200 flex items-center justify-center text-xs font-medium text-gray-600 cursor-pointer hover:bg-gray-300 transition-colors overflow-hidden"
                                    onClick={() => setActivePopup(activePopup === 'profile' ? 'none' : 'profile')}
                                >
                                    {user && user.photoURL ? (
                                        <img src={user.photoURL} alt="Profile" className="w-full h-full object-cover" />
                                    ) : (
                                        user && user.displayName ? user.displayName[0].toUpperCase() : "BA"
                                    )}
                                </div>
                            </Tooltip>

                            {/* Profile Popup */}
                            {activePopup === 'profile' && (
                                <>
                                    <div className="fixed inset-0 z-30" onClick={() => setActivePopup('none')} />
                                    <div className="absolute top-full right-0 mt-2 w-auto min-w-[200px] bg-white rounded-2xl shadow-xl border border-gray-200 overflow-hidden z-40 flex flex-col py-1 animate-slide-up-fade">
                                        {user ? (
                                            <>
                                                <div className="px-4 py-3 border-b border-gray-100">
                                                    <p className="text-xs font-medium text-gray-900">{user.displayName}</p>
                                                    <p className="text-[10px] text-gray-500 truncate">{user.email}</p>

                                                </div>

                                                <button
                                                    onClick={handleSwitchAccount}
                                                    className="flex items-center gap-2 px-4 py-2.5 text-xs text-gray-700 hover:bg-gray-50 w-full text-left transition-colors"
                                                >
                                                    <Users className="w-3.5 h-3.5" />
                                                    Switch Account
                                                </button>
                                                <button
                                                    onClick={handleLogout}
                                                    className="flex items-center gap-2 px-4 py-2.5 text-xs text-red-600 hover:bg-red-50 w-full text-left transition-colors"
                                                >
                                                    <LogOut className="w-3.5 h-3.5" />
                                                    Logout
                                                </button>
                                            </>
                                        ) : (
                                            <div className="p-4 flex flex-col gap-3">
                                                <p className="text-xs text-gray-600 text-center">Sign in to sync history and upgrade.</p>
                                                <button
                                                    onClick={handleLogin}
                                                    className="flex items-center justify-center gap-2 w-full py-2 bg-black text-white rounded-lg hover:bg-gray-800 transition-colors text-xs font-medium"
                                                >
                                                    <Users className="w-3.5 h-3.5" />
                                                    Sign in with Google
                                                </button>
                                                <button
                                                    onClick={() => window.open('https://accounts.google.com/signin/recovery', '_blank')}
                                                    className="text-[10px] text-gray-400 hover:text-gray-600 transition-colors text-center w-full"
                                                >
                                                    Forgot Password?
                                                </button>
                                            </div>
                                        )}
                                    </div>
                                </>
                            )}
                        </div>
                        {summary ? (
                            <div
                                key="summary-content"
                                className="flex flex-col h-full relative animate-fade-in"
                            >
                                {/* Floating Back Button */}
                                <div className="absolute top-4 left-4 z-30">
                                    <Tooltip content="Back" side="bottom">
                                        <Button
                                            variant="secondary"
                                            size="icon"
                                            onClick={handleBack}
                                            className="rounded-full w-8 h-8 shadow-sm border-gray-200 bg-white/80 backdrop-blur-sm"
                                        >
                                            <ArrowLeft className="w-4 h-4 text-gray-600" />
                                        </Button>
                                    </Tooltip>
                                </div>

                                {/* Top Solid Header Mask */}
                                <div className="absolute top-0 left-0 right-0 h-16 bg-white z-20 border-b border-gray-50" />


                                {/* Content */}
                                {isEditing ? (
                                    <textarea
                                        value={summary}
                                        onChange={(e) => setSummary(e.target.value)}
                                        onBlur={() => setIsEditing(false)}
                                        autoFocus
                                        className="flex-1 w-full resize-none p-6 pt-20 pb-20 text-sm leading-relaxed text-gray-700 text-justify font-sans border-none focus:ring-0 outline-none"
                                    />
                                ) : (
                                    <div className="flex-1 overflow-y-auto text-sm leading-relaxed text-gray-700 text-justify font-sans p-6 pt-20 pb-40">
                                        {summary}
                                    </div>
                                )}

                                {/* Bottom Section (inside card overlay) */}
                                <div className="absolute bottom-0 left-0 right-0 flex flex-col items-end gap-3 bg-gradient-to-t from-white via-white/95 to-transparent pt-12 pb-4 px-4">

                                    {/* Disclaimer */}
                                    <div className="w-full text-center">
                                        <span className="text-[10px] text-gray-500 bg-gray-50 px-3 py-1 rounded-full border border-gray-100 opacity-80">
                                            {provider === 'google' ? 'Gemini' : provider === 'openai' ? 'ChatGPT' : 'AI'} can make mistakes. Regenerate if needed.
                                        </span>
                                    </div>

                                    {/* Floating Toolbar */}
                                    <SummaryToolbar
                                        summary={summary}
                                        onEdit={() => setIsEditing(true)}
                                        activePopup={activePopup}
                                        onTogglePopup={setActivePopup}
                                        onRegenerate={handleRegenerate}
                                        user={user}
                                    />
                                </div>
                            </div>
                        ) : (
                            <div
                                key="empty-state"
                                className="w-full h-full animate-fade-in p-6 pt-16 flex items-start"
                            >
                                <span className="text-gray-400 text-sm">Ready to generate summary</span>
                            </div>
                        )}
                    </div>
                </div>

                {/* Fixed Bottom Section */}
                <div className="shrink-0 flex flex-col gap-4 pb-2 relative z-50">
                    <GenerateButton
                        onGenerate={handleGenerate}
                        state={genState}
                        isRegenerating={isRegenerating}
                    />

                    <div className="space-y-3 px-1">
                        <CheckboxRow
                            label="Include AI responses"
                            subtext="Summarize the full conversation"
                            checked={includeAI}
                            onChange={() => {
                                setIncludeAI(prev => !prev);
                            }}
                        />
                        <CheckboxRow
                            label="Read images"
                            subtext="Include visual context"
                            checked={analyzeImages}
                            onChange={() => {
                                setAnalyzeImages(prev => !prev);
                            }}
                        />
                    </div>

                    {/* Bottom Buttons Row */}
                    <div className="relative flex items-center justify-between pt-2 px-1">
                        <div className="relative z-[110]">
                            <Tooltip content="Metadata">
                                <Button
                                    variant="secondary"
                                    size="icon"
                                    className={cn(
                                        "relative z-20 rounded-full w-9 h-9 shadow-sm border-gray-200 text-gray-500 transition-colors hover:bg-gray-50",
                                        activePopup === 'metadata' && "bg-gray-100 text-gray-900 border-gray-300"
                                    )}
                                    onClick={() => setActivePopup(activePopup === 'metadata' ? 'none' : 'metadata')}
                                >
                                    <Info className="w-4 h-4" />
                                </Button>
                            </Tooltip>
                            {activePopup === 'metadata' && (
                                <>
                                    <div className="fixed inset-0 z-[90]" onClick={() => setActivePopup('none')} />
                                    <div className="absolute bottom-full left-0 mb-2 z-[100] w-[280px] bg-white rounded-2xl shadow-xl border border-gray-200 p-5 text-sm origin-bottom-left">
                                        <h3 className="font-semibold text-gray-900 mb-4">Metadata</h3>
                                        <div className="space-y-3 text-gray-600">
                                            <div className="flex justify-between items-center">
                                                <span>Version</span>
                                                <span className="font-medium text-gray-900 bg-gray-100 px-2 py-0.5 rounded text-xs">Tiger v1.0</span>
                                            </div>
                                            <div className="flex justify-between items-center">
                                                <span>Engine</span>
                                                <span className="font-medium text-gray-900">GPT-4o-mini</span>
                                            </div>
                                            <div className="flex justify-between items-center">
                                                <span>Status</span>
                                                <span className="flex items-center gap-1.5 font-medium text-green-600 text-xs bg-green-50 px-2 py-0.5 rounded-full border border-green-100">
                                                    <span className="w-1.5 h-1.5 rounded-full bg-green-600 animate-pulse" />
                                                    Active
                                                </span>
                                            </div>
                                            <div className="flex justify-between items-center">
                                                <span>Developer</span>
                                                <span className="font-medium text-gray-900">Bharath Amaravadi</span>
                                            </div>
                                            <div className="pt-3 mt-1 border-t border-gray-100">
                                                <button
                                                    onClick={() => chrome.tabs.create({ url: chrome.runtime.getURL('welcome.html') })}
                                                    className="flex items-center justify-center gap-2 w-full py-2 bg-black text-white rounded-lg hover:bg-gray-800 transition-colors font-medium text-xs"
                                                >
                                                    Visit Website
                                                    <ExternalLink className="w-3 h-3" />
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </>
                            )}
                        </div>

                        <div className="flex items-center gap-2 z-[110]">
                            <div className="relative">
                                <Tooltip content="Feedback">
                                    <Button
                                        variant="secondary"
                                        size="icon"
                                        className="relative z-20 rounded-full w-9 h-9 shadow-sm border-gray-200 text-gray-500 transition-colors hover:bg-gray-50"
                                        onClick={() => setActivePopup(activePopup === 'feedback' ? 'none' : 'feedback')}
                                    >
                                        <MessageSquare className="w-4 h-4" />
                                    </Button>
                                </Tooltip>
                                {activePopup === 'feedback' && (
                                    <div className="fixed inset-0 z-[90]" onClick={() => setActivePopup('none')} />
                                )}
                                <PulseCheck
                                    open={activePopup === 'feedback'}
                                    onOpenChange={(open) => setActivePopup(open ? 'feedback' : 'none')}
                                    userEmail={user?.email}
                                />
                            </div>
                            <div className="relative">
                                <Tooltip content="History">
                                    <Button
                                        variant="secondary"
                                        size="icon"
                                        className={cn(
                                            "relative z-20 rounded-full w-9 h-9 shadow-sm border-gray-200 text-gray-500 transition-colors hover:bg-gray-50",
                                            activePopup === 'history' && "bg-gray-100 text-gray-900 border-gray-300"
                                        )}
                                        onClick={() => setActivePopup(activePopup === 'history' ? 'none' : 'history')}
                                    >
                                        <History className="w-4 h-4" />
                                    </Button>
                                </Tooltip>
                                {activePopup === 'history' && (
                                    <>
                                        <div className="fixed inset-0 z-[90]" onClick={() => setActivePopup('none')} />
                                        <div className="absolute bottom-full right-0 mb-2 z-[100] w-[340px] bg-white rounded-2xl shadow-xl border border-gray-200 p-5 text-sm origin-bottom-right">
                                            <div className="flex justify-between items-center mb-4">
                                                <h3 className="font-semibold text-gray-900">History</h3>
                                                <button
                                                    onClick={handleClearHistory}
                                                    className="text-[10px] font-medium text-red-500 hover:text-red-600 transition-colors"
                                                >
                                                    Clear all
                                                </button>
                                            </div>
                                            <div className="space-y-3 max-h-[250px] overflow-y-auto pr-1 custom-scrollbar">
                                                {history.length === 0 ? (
                                                    <div className="text-center text-gray-400 py-8">
                                                        <History className="w-8 h-8 mx-auto mb-2 opacity-50" />
                                                        <p>No history yet</p>
                                                    </div>
                                                ) : (
                                                    history.map((item) => (
                                                        <div
                                                            key={item.id}
                                                            onClick={() => handleViewHistoryItem(item)}
                                                            className="flex flex-col gap-1 p-3 rounded-xl bg-gray-50 border border-gray-100 hover:border-gray-200 transition-colors cursor-pointer shrink-0"
                                                        >
                                                            <div className="flex justify-between items-start">
                                                                <span className="font-medium text-xs text-gray-900 line-clamp-1">Summary</span>
                                                                <span className="text-[10px] text-gray-400 whitespace-nowrap ml-2">
                                                                    {new Date(item.date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                                                                </span>
                                                            </div>
                                                            <p className="text-[10px] text-gray-500 line-clamp-2 leading-relaxed">
                                                                {item.preview}
                                                            </p>
                                                        </div>
                                                    ))
                                                )}
                                            </div>
                                            {history.length > 0 && (
                                                <button
                                                    onClick={() => {/* TODO: View All Page */ }}
                                                    className="w-full py-2 text-xs font-medium text-gray-500 hover:text-gray-900 transition-colors"
                                                >
                                                    View all history
                                                </button>
                                            )}
                                        </div>
                                    </>
                                )}
                            </div>

                            <div className="relative">
                                <Tooltip content="Settings">
                                    <Button
                                        variant="secondary"
                                        size="icon"
                                        className={cn(
                                            "relative z-20 rounded-full w-9 h-9 shadow-sm border-gray-200 text-gray-500 transition-colors hover:bg-gray-50"
                                        )}
                                        onClick={() => setActivePopup(activePopup === 'settings' ? 'none' : 'settings')}
                                    >
                                        <Settings className="w-4 h-4" />
                                    </Button>
                                </Tooltip>
                                {activePopup === 'settings' && (
                                    <>
                                        <div className="fixed inset-0 z-[90]" onClick={() => setActivePopup('none')} />
                                        <div className="absolute bottom-full right-0 mb-2 z-[100] w-[200px] bg-white rounded-2xl shadow-xl border border-gray-200 p-5 text-sm origin-bottom-right max-h-[400px] overflow-y-auto custom-scrollbar">
                                            <h3 className="font-semibold text-gray-900 mb-4">Settings</h3>
                                            <div className="space-y-4">
                                                {false && (
                                                    <>
                                                        {/* Model Provider Selection */}
                                                        <div className="space-y-2">
                                                            <label className="text-xs font-medium text-gray-700">Model Provider</label>
                                                            <div className="flex bg-gray-100 p-1 rounded-lg gap-1">
                                                                <button
                                                                    onClick={() => handleProviderChange('auto')}
                                                                    className={cn(
                                                                        "flex-1 py-1.5 text-[10px] font-medium rounded-md transition-all flex items-center justify-center gap-1",
                                                                        provider === 'auto' ? "bg-white text-black shadow-sm font-bold" : "text-gray-500 hover:text-gray-900"
                                                                    )}
                                                                >
                                                                    <Sparkles className="w-3 h-3" />
                                                                    Auto
                                                                </button>
                                                                <button
                                                                    onClick={() => handleProviderChange('openai')}
                                                                    className={cn(
                                                                        "flex-1 py-1.5 text-[10px] font-medium rounded-md transition-all",
                                                                        provider === 'openai' ? "bg-white text-gray-900 shadow-sm" : "text-gray-500 hover:text-gray-900"
                                                                    )}
                                                                >
                                                                    OpenAI
                                                                </button>
                                                                <button
                                                                    onClick={() => handleProviderChange('google')}
                                                                    className={cn(
                                                                        "flex-1 py-1.5 text-[10px] font-medium rounded-md transition-all",
                                                                        provider === 'google' ? "bg-white text-gray-900 shadow-sm" : "text-gray-500 hover:text-gray-900"
                                                                    )}
                                                                >
                                                                    Gemini
                                                                </button>
                                                            </div>
                                                        </div>

                                                        <div className="space-y-1.5">
                                                            <label className="text-xs font-medium text-gray-700">API Key <span className="text-gray-400 font-normal">(Optional)</span></label>
                                                            <p className="text-[10px] text-gray-500 leading-relaxed">
                                                                Choose your preferred AI model. "Auto" uses OpenAI for speed and Google Gemini for large contexts.
                                                            </p>
                                                        </div>
                                                    </>
                                                )}
                                                <div className="space-y-2">
                                                    <label className="text-xs font-medium text-gray-700">Summary Type</label>
                                                    <div className="flex flex-col gap-2">
                                                        {(['TXT', 'JSON', 'XML'] as const).map((type) => (
                                                            <label
                                                                key={type}
                                                                className="flex items-center gap-3 p-2 rounded-lg border border-gray-100 hover:bg-gray-50 cursor-pointer transition-colors"
                                                            >
                                                                <div className={cn(
                                                                    "w-4 h-4 rounded-full border flex items-center justify-center transition-all",
                                                                    summaryType === type ? "border-black bg-black" : "border-gray-300 bg-white"
                                                                )}>
                                                                    {summaryType === type && <div className="w-1.5 h-1.5 rounded-full bg-white" />}
                                                                </div>
                                                                <input
                                                                    type="radio"
                                                                    name="summaryType"
                                                                    value={type}
                                                                    checked={summaryType === type}
                                                                    onChange={() => setSummaryType(type)}
                                                                    className="hidden"
                                                                />
                                                                <span className="text-xs font-medium text-gray-700">{type}</span>
                                                            </label>
                                                        ))}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </>
                                )}
                            </div>

                            <div className="relative">
                                <Tooltip content="Help">
                                    <Button
                                        variant="secondary"
                                        size="icon"
                                        className={cn(
                                            "relative z-20 rounded-full w-9 h-9 shadow-sm border-gray-200 text-gray-500 transition-colors hover:bg-gray-50"
                                        )}
                                        onClick={() => setActivePopup(activePopup === 'help' ? 'none' : 'help')}
                                    >
                                        <HelpCircle className="w-4 h-4" />
                                    </Button>
                                </Tooltip>
                                {activePopup === 'help' && (
                                    <>
                                        <div className="fixed inset-0 z-[90]" onClick={() => setActivePopup('none')} />
                                        <div className="absolute bottom-full right-0 mb-2 z-[100] w-max bg-white rounded-2xl shadow-xl border border-gray-200 p-5 text-sm origin-bottom-right">
                                            <h3 className="font-semibold text-gray-900 mb-4">Help & Support</h3>
                                            <div className="space-y-3">
                                                <button
                                                    onClick={() => handleHelpAction('docs')}
                                                    className="flex items-center gap-3 w-full text-left text-gray-600 hover:text-gray-900 transition-colors"
                                                >
                                                    <Book className="w-4 h-4" />
                                                    Documentation
                                                </button>
                                                <button
                                                    onClick={() => handleHelpAction('faqs')}
                                                    className="flex items-center gap-3 w-full text-left text-gray-600 hover:text-gray-900 transition-colors"
                                                >
                                                    <HelpCircle className="w-4 h-4" />
                                                    FAQs
                                                </button>
                                                <button
                                                    onClick={() => handleHelpAction('support')}
                                                    className="flex items-center gap-3 w-full text-left text-gray-600 hover:text-gray-900 transition-colors"
                                                >
                                                    <Mail className="w-4 h-4" />
                                                    Contact Support
                                                </button>
                                            </div>
                                        </div>
                                    </>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    );
};
